---
services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:16-0.106.0-ferretdb-2.5.0
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file:
      - ../komodo/secrets.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${KOMODO_DB_USERNAME}
      POSTGRES_PASSWORD: ${KOMODO_DB_PASSWORD}
      POSTGRES_DB: postgres

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.5.0
    labels:
      komodo.skip:
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ../komodo/secrets.env
    volumes:
      - ferretdb-state:/state
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@postgres:5432/postgres
  
  core:
    image: ghcr.io/moghtech/komodo-core:1.19.5
    labels:
      komodo.skip:
    restart: unless-stopped
    depends_on:
      - ferretdb
    env_file:
      - ../komodo/compose.env
      - ../komodo/secrets.env
    ports:
      - 127.0.0.1:9120:9120
    environment:
      KOMODO_DATABASE_ADDRESS: ferretdb:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19.5
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file: 
      - ../komodo/compose.env
      - ../komodo/secrets.env
    environment:
      PERIPHERY_PASSKEYS: ${KOMODO_PASSKEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo

volumes:
  postgres-data:
  ferretdb-state:
