---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:0.8.9
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Berlin"
    volumes:
      - ${EXT_PATH}/kavita/config:/config
      - ${EXT_PATH}/media:/media
    ports:
      - ${KAVITA_HTTP_PORT:-5001}:5000
    cpus: 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
