---
services:
  subnet-router:
    image: "ghcr.io/tailscale/tailscale:v1.92.5"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_HOSTNAME: ${TS_HOSTNAME}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      TS_AUTHKEY: ${TS_OAUTH_SECRET}
      TS_ROUTES: ${TS_ROUTES}
      TS_EXTRA_ARGS: --advertise-tags=tag:${TS_TAG}
      TS_SERVE_CONFIG: /tailscale-serve.json
    volumes:
      - ts-state:/var/lib/tailscale
      - ./serve.json:/tailscale-serve.json:ro

volumes:
  ts-state:
