---
services:
  immich:
    image: ghcr.io/immich-app/immich-server:v2.0.1
    restart: unless-stopped
    network_mode: "service:tailscale"
    volumes:
      - ${EXT_PATH}/immich:/data
      - ${EXT_PATH}/photos:/mnt/media/photos:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: Europe/Berlin
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: localhost
      DB_HOSTNAME: localhost
    depends_on:
      - redis
      - database

  redis:
    restart: unless-stopped
    network_mode: "service:tailscale"
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    restart: unless-stopped
    network_mode: "service:tailscale"
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:c44be5f2871c59362966d71eab4268170eb6f5653c0e6170184e72b38ffdf107
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_STORAGE_TYPE: "HDD"
    volumes:
      - ${EXT_PATH}/immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
