---
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.1.3
    restart: unless-stopped
    ports:
      - "127.0.0.1:8123:8123"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${EXT_PATH}/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
