---
services:
  immich:
    image: ghcr.io/immich-app/immich-server:v2.4.1
    restart: unless-stopped
    ports:
      - 2283:2283
      # API for metrics
      - 127.0.0.1:8081:8081
    volumes:
      - ${EXT_PATH}/immich:/data
      - ${EXT_PATH}/photos:/mnt/media/photos:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: Europe/Berlin
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
      DB_HOSTNAME: database
      IMMICH_MACHINE_LEARNING_URL: http://machine-learning:3003
      IMMICH_METRICS: "true"
      IMMICH_TELEMETRY_INCLUDE: "all"
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8081"
      - "prometheus.io/path=/metrics"
    depends_on:
      - redis
      - database
      - machine-learning

  redis:
    restart: unless-stopped
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    restart: unless-stopped
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_STORAGE_TYPE: "HDD"
    volumes:
      - ${EXT_PATH}/immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
    restart: unless-stopped
    volumes:
      - ${EXT_PATH}/immich/model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: Europe/Berlin
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g
