services:
  stirling-pdf:
    image: ghcr.io/stirling-tools/stirling-pdf:2.1.5
    restart: unless-stopped
    network_mode: "service:tailscale"
    volumes:
      - ${EXT_PATH}/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ${EXT_PATH}/StirlingPDF/extraConfigs:/configs
      - ${EXT_PATH}/StirlingPDF/customFiles:/customFiles/
      - ${EXT_PATH}/StirlingPDF/logs:/logs/
      - ${EXT_PATH}/StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
